version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: berilo123
      POSTGRES_DB: projeto01

volumes:
  postgres-disk:
